server:
  port: 8083

spring:
  application:
    name: courier-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/courier
    username: ${POSTGRES_USER:courier}
    password: ${POSTGRES_PASSWORD:courier123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: db.changelog/master.changelog.xml


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics



logging:
  level:
    com.orhanararat: DEBUG
    org.springframework.kafka: WARN
